version: '3.8'

services:
  postgres-db:
    image: postgres:15
    env_file:
      - env/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: user/springboot-app
    depends_on:
      - postgres-db
    ports:
      - "8081:8080"
    env_file:
      - env/.env

networks:
  ci_network:
      driver: bridge

volumes:
  postgres_data: